filter.append("feColorMatrix")
    .attr("type", "matrix")
    .attr("values", "0 0 0 0   0 0 0 0 0   0 0 0 0 0   0 0 0 0 0.1 0")
    filter.append("feGaussianBlur")
    .attr("stdDeviation","5")
    .attr("result","coloredBlur")
const feMerge = filter.append("feMerge")
feMerge.append("feMergeNode").attr("in","coloredBlur")
feMerge.append("feMergeNode").attr("in","SourceGraphic")